name: argocd chart update

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  # TODO: Cleanup after testing
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 0 * * 1" # 00:00 on Mondays

jobs:
  update-embedded-argocd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          sparse-checkout: |
            cmd/yokecd-installer/argocd

      - name: Check for new ArgoCD Chart version
        id: diff
        shell: bash
        run: |
          cd cmd/yokecd-installer/argocd
          rm -f argo-cd-*.tgz

          # https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/Chart.yaml
          CHART_INDEX_URL="https://argoproj.github.io/argo-helm/index.yaml"
          CHART_ENTRY="$(curl -fsSL "$CHART_INDEX_URL" | yq '.entries."argo-cd"[0]')"
          CHART_URL="$(echo "$CHART_ENTRY" | yq -r '.urls[0]')"
          curl -fsSLO "$CHART_URL"

          if ! git diff --quiet; then
            echo "new version detected (${VERSION}), opening PR..."
            CHART_VERSION="$(echo "$CHART_ENTRY" | yq -r '.version')"
            echo "version=$CHART_VERSION" >> "$GITHUB_OUTPUT"
          fi

      - name: Create PR
        if: steps.diff.outputs.version != ''
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail

          BRANCH="yokecd-installer/argocd-chart-upgrade"
          TITLE="yokecd-installer: bump ArgoCD Chart to ${{ steps.diff.outputs.version }}"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "$TITLE"
          git push origin "$BRANCH" --force

          PR_NUMBER_EXISTING="$(gh pr view "$BRANCH" --json number -q .number 2>/dev/null || true)"

          if [ -z "$PR_NUMBER_EXISTING" ]; then
            PR_NUMBER_NEW="$(gh pr create \
              --title "$TITLE" \
              --body "Automated update of embedded ArgoCD Helm Chart." \
              --base main \
              --head "$BRANCH" \
              --json number -q .number)"
            # TODO: Identify upstream branch protection rules and implement accordingly
            # gh pr merge "$PR_NUMBER_NEW" --auto --merge
          fi
